luajit-lanes: Version bump to v3.16.2
Version bump to upstream 3.16.2 release. Removed deprecated patches. Add new patch to resolve:
`tools.c:1511:34: error: 'CLONABLES_CACHE_KEY' defined but not used [-Werror=unused-const-variable=]`

Signed-off-by: Mark Baker <mark@vpost.net>